server:
  port: 8081

spring:
  application:
    name: Mandate Management System

mandate:
  pattern:
    inbound: MNDT-*.csv
  path:
    base-dir: /Users/jeevan/Downloads/mandate
    inbound: ${mandate.path.base-dir}/inbound
    processed: ${mandate.path.base-dir}/processed
    failed: ${mandate.path.base-dir}/failed
    outbound: ${mandate.path.base-dir}/outbound