server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
    enabled-by-default: 'true'
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: Mandate Management System
  datasource:
    url: jdbc:postgresql://localhost:5432/mms
    username: jeevan
    password: root
    hikari:
      connection-timeout: 3000
      minimum-idle: 10
      maximum-pool-size: 40
      pool-name: mms-connection-pool
      max-lifetime: 10000
      auto-commit: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    enabled: true
    change-log: classpath:db/db-changelog-master.yaml

mandate:
  pattern:
    inbound: MNDT-*.csv
  path:
    base-dir: /Users/jeevan/Downloads/mandate
    inbound: ${mandate.path.base-dir}/inbound
    processed: ${mandate.path.base-dir}/processed
    failed: ${mandate.path.base-dir}/failed
    outbound: ${mandate.path.base-dir}/outbound